services:
  termix:
    #image: ghcr.io/lukegus/termix:latest
    image: ghcr.io/lukegus/termix:dev-1.0-development-latest
    container_name: termix
    restart: unless-stopped
    ports:
      - "3800:8080"
    volumes:
      - termix-data:/app/data
    environment:
      # Generate random salt here https://www.lastpass.com/features/password-generator (max 32 characters, include all characters for settings)
      SALT: "2v.F7!6a!jIzmJsu|[)h61$ZMXs;,i+~"

volumes:
  termix-data:
    driver: local 