name: Docker Build and Push

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Optional: Tag to use instead of auto-incrementing'
        required: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Environment Variables
      run: |
        REPO_OWNER=${GITHUB_REPOSITORY%/*} # Extract the owner from the repo slug
        echo "REPO_OWNER=${REPO_OWNER}" >> $GITHUB_ENV
        if [ -n "${{ github.event.inputs.tag_name }}" ]; then
          echo "IMAGE_TAG=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
        else
          # Fetch all testing-* tags and determine the next build number
          all_tags=$(curl -s "https://api.github.com/repos/${REPO_OWNER}/${{ github.repository }}/tags")
          last_build_number=$(echo "$all_tags" | jq -r 'map(select(.name | startswith("testing-"))) | .[].name' | sed 's/^testing-//' | sort -n | tail -n 1)
          
          if [[ -z "$last_build_number" ]]; then
            next_build_number=1
          else
            next_build_number=$((last_build_number + 1))
          fi
          
          echo "IMAGE_TAG=testing-${next_build_number}" >> $GITHUB_ENV
        fi

    - name: Debug Environment Variables
      run: |
        echo "REPO_OWNER=${{ env.REPO_OWNER }}"
        echo "IMAGE_TAG=${{ env.IMAGE_TAG }}"

    - name: Log into GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        tags: ghcr.io/${{ env.REPO_OWNER }}/ssh-project:${{ env.IMAGE_TAG }}